first-job:
  file:
    name: "github-example.csv"
    limit: 1000
  host: "cPath"

second-job:
  file:
    name: "github-example2.csv"
    limit: 1000
  host: "cPath2"

database:
  username: "username"
  password: "password"
  url: "http:"
  schema: "schema"

